name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: Push to central
        run: |
          ./gradlew publishAllToNewMavenCentralApi --info -Psign=true \
            -PprojVersion=${GITHUB_REF_NAME#v} \
            -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
            -PcentralApiUsername=${{ secrets.MAVENCENTRAL_USERNAME }} \
            -PcentralApiPassword=${{ secrets.MAVENCENTRAL_PASSWORD }} \
            -PsigningKey="${{ secrets.SIGNING_KEY }}" \
            -PautomaticPublish=true \
            -PwaitForPublished=false